timezone: Asia/Jakarta
encoding: utf-8
exclude: [vendor]
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
